### ISSUE TITLE
您好 请问下脚本现在还可以用吗

### ISSUE THREAD

**Issue by spring59** [chacuavip10/oci_auto#2]
oracle检测到使用脚本 会不会被封号啊

**Comment by kainjinez** [comment]
Till now. No

**Comment by spring59** [comment]
已经用这个脚本跑了两三天了  东京的 还在跑！谢谢提供脚本！thank you

**Comment by kainjinez** [comment]
It tooks me around 5 hours to get my own at Singapore Region. But Japan looks cramped to be able to register.
