### ISSUE TITLE
Invalid ssh public key; must be in base64 format

### ISSUE THREAD

**Issue by leon-titan** [chacuavip10/oci_auto#3]
The log is:

{'opc-request-id': 'XXXXXX', 'code': 'InvalidParameter', 'message': 'Invalid ssh public key; must be in base64 format', 'status': 400}

How to deal with this?

**Comment by chacuavip10** [comment]
Your ssh key format should look like this:
`ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCuZtQECOunRof+76yhTmy+YH/hdU09SkQIe4AGCgucIcZF0FWK9mGwBJQk26Vwm81Yc054CSvDKppOIGirvM4ooA0cod6DLxmI4R2rO8K1otoJ2FwKEK/gIfGKHrZKVUJtHlccJi5cfvID8wd1e0DRpzdUamzIS2kGNrPZZtF3MGUcYqNDgg+gqMrg0qiMQr21wH0NGdsnWSQHomCLxWPl3dvRIK1lzg6xnikoiSJDw/gDrnm+62bHm41luAWXy99CMOakIt3icFqig0GBQ77DI8Oa4zzQECYX6xuXozYZqr3d123124H58aBy8KkF7McrCPLqrSLhdmEoS4BtavePLs+3nS/DDmYIHT43Zg6Y6XIYYq/UvqMmcDnrdXAljmeLXViZlJWBgLvhBS2fh2HDZ3o8V/eopcUSqxPagb5jBbdsYqpag8IIyM+TOgel0OHqo2vTvSkjFw8DeM+jQcpmUVADNToznhH1Veymg46VEuE= username@hostname`
If you have multiple key, add \n between key.

**Comment by leon-titan** [comment]
Cool, got it. Thx.
