### ISSUE TITLE
Repo is missing license

### ISSUE THREAD

**Issue by Wulf-Steppen** [chacuavip10/oci_auto#6]
GitHub's TOS is fairly clear that in the absence of a declared license that default copyright laws apply. Github's TOS also allows for public repositories to be forked so long as the fork remains on GitHub. I'd like to make derivative work on this code, but in the absence of a license I am limited in my legal rights to do so.

So, can you attach a license or can I have permission to iterate or build on the code available in this repo for my own application?

**Comment by chacuavip10** [comment]
Sorry i'm not really active on github, basiclly you can use the script for anything you want, no permission needed. I'm not familiar with license, basic googling said MIT is okey right?
